### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.pkl'

### ISSUE THREAD

**Issue by avinash321** [someshkhandelia/Final-Year-Project#1]
Hi, getting following error while running  AttendanceTaker.py
$ python3 AttendanceTaker.py
Taking image...
############## FACE DETECTION COMPLETED !! ##################
Traceback (most recent call last):
  File "AttendanceTaker.py", line 52, in <module>
    predictions = ifk_obj.getPrediction(trained_pickle_name)
  File "C:\Users\avinash\Desktop\test\Final-Year-Project\ImageFeederKNN.py", line 48, in getPrediction
    self.KNN_classifier = self.KNN_obj.loadClassifier(pickle_name)
  File "C:\Users\avinash\Desktop\test\Final-Year-Project\KNNClassifier.py", line 57, in loadClassifier
    with open(pickle_name + '.pkl' , 'rb') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '.pkl'

**Comment by someshkhandelia** [comment]
I have not kept the trained classifier's pickle file on github since it was too large.
You can train the classifier, create the pkl file and then use it in AttendanceTaker.py

**Comment by someshkhandelia** [comment]
TrainClassifier.py would do the job for you.
