### ISSUE TITLE
Query data dimension does not match training data.

### ISSUE THREAD

**Issue by Adarsh8960** [someshkhandelia/Final-Year-Project#2]
Traceback (most recent call last):
  File "C:\Users\Adarsh\Desktop\FYP\Final-Year-Project-master\AttendanceTaker.py", line 52, in <module>
    predictions = ifk_obj.getPrediction('KNN_Classifier_80_TrainingData_92_percent_accurate')
  File "C:\Users\Adarsh\Desktop\FYP\Final-Year-Project-master\ImageFeederKNN.py", line 49, in getPrediction
    self.predicted_results = self.KNN_classifier.predict(self.array_of_images)
  File "C:\Program Files\Python35\lib\site-packages\sklearn\neighbors\classification.py", line 145, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "C:\Program Files\Python35\lib\site-packages\sklearn\neighbors\base.py", line 385, in kneighbors
    for s in gen_even_slices(X.shape[0], n_jobs)
  File "C:\Program Files\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Program Files\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Program Files\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Program Files\Python35\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "C:\Program Files\Python35\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "C:\Program Files\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "C:\Program Files\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "sklearn\neighbors\binary_tree.pxi", line 1294, in sklearn.neighbors.kd_tree.BinaryTree.query
ValueError: query data dimension must match training data dimension

**Comment by someshkhandelia** [comment]
In AttendanceTaker.py
Add this in line 30:

img = cv2.imread("captured_image.jpg",0)
